In [1]:
import numpy as np
import pandas as pd

In [2]:
def possible(y,x,n):
    global grid
    for i in range(0,9) :
        if grid[y][i] == n :
            return False
    for i in range(0,9) :
        if grid[i][x] == n :
            return False
    x0 =  (x//3)*3
    y0 =  (y//3)*3
    
    for i in range(0,3) :
        for j in range(0,3) :
            if grid[y0+i][x0+j] == n :
                return False
    return True

In [3]:
def solve():
    global grid 
    for y in range(9):
        for x in range(9):
            if grid [y][x] == 0 :
                for n in range(1,10) :
                    if possible(y,x,n) :
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input("More?")

In [6]:
grid = [[2,0,0,0,8,0,0,1,0],
        [0,4,0,1,0,0,3,0,0],
        [0,0,0,0,9,0,0,0,0],
        [0,0,0,7,0,0,8,4,0],
        [0,9,0,0,2,1,0,0,0],
        [0,0,6,0,0,0,0,0,0],
        [0,3,0,0,0,0,5,8,0],
        [1,0,0,8,0,0,0,0,7],
        [0,2,7,0,5,3,0,0,0]]

In [7]:
solve()

[[2 7 3 5 8 6 9 1 4]
 [5 4 9 1 7 2 3 6 8]
 [6 8 1 3 9 4 7 2 5]
 [3 1 2 7 6 5 8 4 9]
 [7 9 8 4 2 1 6 5 3]
 [4 5 6 9 3 8 1 7 2]
 [9 3 4 2 1 7 5 8 6]
 [1 6 5 8 4 9 2 3 7]
 [8 2 7 6 5 3 4 9 1]]
More?
